// Builds the renderer for the desktop app.
//
// The web source tree is never modified — not even temporarily. This script
// stages a filtered *copy* of it under desktop/staged/ and runs `next build`
// there, which is what makes "the web app stays exactly as it is" a property of
// the build system rather than a promise someone has to remember to keep. A
// crashed build can't leave the working tree half-patched, because it never
// patched anything.
//
// What the copy leaves out, and why each one has to go:
//   proxy.ts        — Proxy (ex-middleware) is unsupported by `output: export`
//   app/api/        — route handlers that read Request are unsupported too
//   app/(auth)/     — no accounts in the desktop build
//   app/dashboard/  — account, storage and subscription management
//   app/lib/server/ — server-only modules (Prisma, better-auth, R2, Paddle)
//   app/manifest.ts — the PWA manifest: meaningless in a packaged desktop app,
//                     and `output: export` rejects the route unless it opts in
//                     with `dynamic = "force-static"`
//
// Next 16 reference: node_modules/next/dist/docs/01-app/02-guides/static-exports.md

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const DESKTOP_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(DESKTOP_DIR, "..");
const STAGED = path.join(DESKTOP_DIR, "staged");

/** Paths (relative to the repo root) that must not reach the desktop build. */
const EXCLUDED = [
  "app/api",
  "app/(auth)",
  "app/dashboard",
  "app/lib/server",
  "app/manifest.ts",
];

const log = (msg) => console.log(`[desktop] ${msg}`);

/**
 * `relPath` must already be normalised to forward slashes.
 *
 * That normalisation is not cosmetic: path.relative() yields backslashes on
 * Windows, so comparing against the forward-slash EXCLUDED entries matched
 * nothing there and the entire exclusion list became a silent no-op — the build
 * then died on the first route that cannot be statically exported.
 */
function isExcluded(relPath) {
  return EXCLUDED.some((ex) => relPath === ex || relPath.startsWith(ex + "/"));
}

function stage() {
  fs.rmSync(STAGED, { recursive: true, force: true });
  fs.mkdirSync(STAGED, { recursive: true });

  // Symlinked, not copied: node_modules is gigabytes and the desktop build
  // needs exactly the dependencies the web build already installed.
  fs.symlinkSync(
    path.join(REPO_ROOT, "node_modules"),
    path.join(STAGED, "node_modules"),
    "junction"
  );

  fs.cpSync(path.join(REPO_ROOT, "app"), path.join(STAGED, "app"), {
    recursive: true,
    filter: (src) => {
      const rel = path.relative(REPO_ROOT, src).split(path.sep).join("/");
      if (isExcluded(rel)) {
        log(`excluded ${rel}`);
        return false;
      }
      return true;
    },
  });

  fs.cpSync(path.join(REPO_ROOT, "public"), path.join(STAGED, "public"), {
    recursive: true,
  });

  for (const file of ["tsconfig.json", "postcss.config.mjs", "package.json"]) {
    fs.copyFileSync(path.join(REPO_ROOT, file), path.join(STAGED, file));
  }

  fs.writeFileSync(path.join(STAGED, "next.config.ts"), desktopNextConfig());
}

// Deliberately not derived from the repo's next.config.ts. That one carries a
// `headers()` block, which `output: export` does not support — and the two
// configs answer different questions anyway: the web app is served by a Node
// server behind a proxy, this is a folder of files read off local disk.
function desktopNextConfig() {
  return `import type { NextConfig } from "next";

// Generated by desktop/build.mjs — do not edit; regenerate instead.
const nextConfig: NextConfig = {
  // A folder of static files, which is what the Electron shell serves over its
  // app:// protocol. No Node server ships with the desktop app.
  output: "export",

  // The repo root, not this staged directory.
  //
  // node_modules here is a symlink up into the repo (see stage()), and Turbopack
  // refuses to follow a symlink that leaves its root — "Symlink
  // [project]/node_modules is invalid, it points out of the filesystem root".
  // Pointing the root at the repo puts the symlink's target back inside it.
  //
  // Both keys carry the same absolute value on purpose: Next warns and prefers
  // outputFileTracingRoot if they disagree, and leaving them unset lets this
  // environment feed Next a Windows-style path that Turbopack turns into a
  // literal "C:\\..." output directory.
  outputFileTracingRoot: ${JSON.stringify(REPO_ROOT)},
  turbopack: { root: ${JSON.stringify(REPO_ROOT)} },

  // Security headers come from the protocol response in desktop/main.js; a
  // static export has no server to emit them, and \`headers()\` is unsupported.
};

export default nextConfig;
`;
}

/**
 * Fail early when node_modules was installed for a different OS.
 *
 * Next compiles with a platform-specific native binary. A checkout shared
 * between WSL and Windows has only one of them installed — whichever `npm
 * install` ran last — and the other side fails deep inside the build with an
 * error that says nothing about the real cause.
 */
function checkPlatformBinaries() {
  const dir = path.join(REPO_ROOT, "node_modules", "@next");
  if (!fs.existsSync(dir)) return;
  const installed = fs.readdirSync(dir).filter((n) => n.startsWith("swc-"));
  if (installed.length === 0) return;

  const want =
    process.platform === "win32" ? "win32" : process.platform === "darwin" ? "darwin" : "linux";
  if (installed.some((n) => n.includes(want))) return;

  console.error(
    `\n[desktop] node_modules was installed for a different platform.\n` +
      `  running on : ${process.platform}\n` +
      `  installed  : ${installed.join(", ")}\n\n` +
      `  Next needs a native compiler binary matching the OS it runs on, and\n` +
      `  Electron's binary is platform-specific too. Either run this build from\n` +
      `  the OS those were installed for, or reinstall node_modules here (which\n` +
      `  will in turn break the other side of a shared checkout).\n`
  );
  process.exit(1);
}

function build() {
  // On Windows the extensionless .bin/next is a shell script that spawnSync
  // cannot execute; the .cmd shim is the entry point, and Node requires a shell
  // to run a .cmd at all.
  const isWindows = process.platform === "win32";
  const next = path.join(REPO_ROOT, "node_modules", ".bin", isWindows ? "next.cmd" : "next");

  const result = spawnSync(isWindows ? `"${next}"` : next, ["build"], {
    cwd: STAGED,
    stdio: "inherit",
    shell: isWindows,
    env: {
      ...process.env,
      // Read by app/lib/platform.ts. Inlined at build time, which is what makes
      // every desktop branch a compile-time constant.
      NEXT_PUBLIC_DESKTOP: "1",
      NODE_ENV: "production",
    },
  });

  // Without this the caller sees a bare "next build failed" for a spawn that
  // never started — no binary, wrong platform, no permission.
  if (result.error) {
    console.error(`[desktop] could not run ${next}:`, result.error.message);
    process.exit(1);
  }
  if (result.status !== 0) {
    console.error(`[desktop] next build failed (exit ${result.status})`);
    process.exit(result.status ?? 1);
  }
}

checkPlatformBinaries();
log("staging renderer sources...");
stage();
log("building static export...");
build();

const out = path.join(STAGED, "out");
if (!fs.existsSync(path.join(out, "index.html"))) {
  console.error(`[desktop] expected ${path.join(out, "index.html")} — export produced nothing`);
  process.exit(1);
}
log(`renderer ready at ${path.relative(REPO_ROOT, out)}`);
